on: push
jobs: 
 build-node:
  runs-on: ubuntu-latest
  container: node:16
  steps:
   - run: node --version
   - uses: actions/checkout@v3
   - run: ls -a
   - run: cd ..
   - run: ls -a
   - run: node app.js
